name: C/C++ CI

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Syntax check for all .cpp files
        run: |
          for file in $(find . -name "*.cpp"); do
            echo "Checking $file"
            g++ -fsyntax-only "$file"
          done

